// Generated by CoffeeScript 1.7.1
(function() {
  var base, exec, httpAddress, puts, repo, siteRunner, sys;

  repo = void 0;

  base = '/Users/nerdfiles/Tools/screenshots/';

  httpAddress = void 0;

  sys = require('sys');

  exec = require('child_process').exec;

  puts = function(error, stdout, stderr) {
    return sys.puts(stdout);
  };

  siteRunner = function() {
    var argv, casper, filename, filenameConstruct, fs, i, links, pageName, process, sep, utils, x, _pageName;
    fs = require('fs');
    process = require('process');
    utils = require('utils');
    casper = require('casper').create({
      verbose: true,
      logLevel: 'debug',
      waitTimeout: 10000,
      stepTimeout: 10000,
      retryTimeout: 150,
      viewportSize: {
        width: 1176,
        height: 806
      },
      pageSettings: {
        loadImages: true,
        loadPlugins: true,
        userAgent: 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv: 22.0) Gecko/20100101 Firefox/22.0',
        webSecurityEnabled: true,
        ignoreSslErrors: true
      },
      onWaitTimeout: function() {
        this.echo('wait timeout');
        this.clear();
        return this.page.stop();
      },
      onStepTimeout: function(timeout, step) {
        this.echo('step timeout');
        this.clear();
        return this.page.stop();
      }
    });
    argv = casper.cli.args;
    casper.on('remote.message', function(msg) {
      return this.echo('remote message caught: ' + msg);
    });
    casper.on('page.error', function(msg, trace) {
      var i, step, _i, _len, _results;
      this.echo('Error: ' + msg, 'ERROR');
      _results = [];
      for (_i = 0, _len = trace.length; _i < _len; _i++) {
        i = trace[_i];
        step = trace[i];
        _results.push(this.echo('   ' + step.file + ' (line ' + step.line + ')', 'ERROR'));
      }
      return _results;
    });
    filename = 'http://google.com';
    links = [];
    if (argv && argv.length > 0) {
      argv.forEach(function(arg, index) {
        if (index === 0) {
          filename = arg;
        }
        if (index > 0) {
          return links.push(arg);
        }
      });
    }
    filenameConstruct = filename.split('//');
    httpAddress = filenameConstruct[1];
    sep = '/';
    exec("mkdir -p " + base + httpAddress, puts);
    x = pageName = _pageName = void 0;
    i = -1;
    casper.start("" + filename, function() {
      x = links;
    });
    casper.then(function() {
      this.each(x, function() {
        var url;
        ++i;
        url = x[i].indexOf('html') !== -1 ? ("" + filename) + sep : "" + filename;
        this.thenOpen(url + x[i], function() {
          this.wait(1000);
          this.capture(base + httpAddress + sep + this.getTitle().replace(/\|/g, '-') + '.png');
        });
      });
    });
    return casper.run();
  };

  siteRunner();

}).call(this);
